import 'package:flutter/material.dart';
import 'package:kscy_2023_frontend/widgets/lecture.dart';

List<String> dailyDesc = [
  "Dart 기초 - 1",
  "Dart 기초 - 2",
  "Dart 기초 - 3",
  "Flutter 기초 - 1",
  "Flutter 기초 - 2",
  "Flutter 심화 - 1",
  "Flutter 심화 - 2",
  "Flutter 심화 - 2",
  "Flutter 심화 - 2",
];

String getDailyValue(int index) {
  return dailyDesc[index];
}

List<List<dynamic>> pages = [
  [
    LectureCard(
        title: "title",
        description: "description",
        day: 3,
        userPref: true,
        complete: true),
    const SizedBox(height: 16),
    LectureCard(
        title: "title",
        description: "description",
        day: 3,
        userPref: false,
        complete: true),
    const SizedBox(height: 16),
    LectureCard(
        title: "title",
        description: "description",
        day: 3,
        userPref: true,
        complete: true),
    const SizedBox(height: 16),
    LectureCard(
        title: "title",
        description: "description",
        day: 3,
        userPref: false,
        complete: true),
    const SizedBox(height: 16),
    LectureCard(
      title: "title",
      description: "description",
      day: 3,
      userPref: false,
      complete: false,
    ),
  ],
  [
    LectureCard(
        title: "title",
        description: "description",
        day: 3,
        userPref: true,
        complete: true),
    const SizedBox(height: 16),
    LectureCard(
        title: "title",
        description: "description",
        day: 3,
        userPref: false,
        complete: false),
    const SizedBox(height: 16),
    LectureCard(
        title: "title",
        description: "description",
        day: 3,
        userPref: false,
        complete: false),
    const SizedBox(height: 16),
    LectureCard(
        title: "title",
        description: "description",
        day: 3,
        userPref: false,
        complete: false),
    const SizedBox(height: 16),
    LectureCard(
      title: "title",
      description: "description",
      day: 3,
      userPref: false,
      complete: false,
    ),
  ],
  [
    LectureCard(
        title: "title",
        description: "description",
        day: 3,
        userPref: true,
        complete: true),
    const SizedBox(height: 16),
    LectureCard(
        title: "title",
        description: "description",
        day: 3,
        userPref: false,
        complete: false),
    const SizedBox(height: 16),
    LectureCard(
        title: "title",
        description: "description",
        day: 3,
        userPref: false,
        complete: false),
    const SizedBox(height: 16),
    LectureCard(
        title: "title",
        description: "description",
        day: 3,
        userPref: false,
        complete: false),
    const SizedBox(height: 16),
    LectureCard(
      title: "title",
      description: "description",
      day: 3,
      userPref: false,
      complete: false,
    ),
  ],
  [
    LectureCard(
        title: "title",
        description: "description",
        day: 3,
        userPref: true,
        complete: true),
    const SizedBox(height: 16),
    LectureCard(
        title: "title",
        description: "description",
        day: 3,
        userPref: false,
        complete: false),
    const SizedBox(height: 16),
    LectureCard(
        title: "title",
        description: "description",
        day: 3,
        userPref: false,
        complete: false),
    const SizedBox(height: 16),
    LectureCard(
        title: "title",
        description: "description",
        day: 3,
        userPref: false,
        complete: false),
    const SizedBox(height: 16),
    LectureCard(
      title: "title",
      description: "description",
      day: 3,
      userPref: false,
      complete: false,
    ),
  ],
  [
    LectureCard(
        title: "title",
        description: "description",
        day: 3,
        userPref: true,
        complete: true),
    const SizedBox(height: 16),
    LectureCard(
        title: "title",
        description: "description",
        day: 3,
        userPref: false,
        complete: false),
    const SizedBox(height: 16),
    LectureCard(
        title: "title",
        description: "description",
        day: 3,
        userPref: false,
        complete: false),
    const SizedBox(height: 16),
    LectureCard(
        title: "title",
        description: "description",
        day: 3,
        userPref: false,
        complete: false),
    const SizedBox(height: 16),
    LectureCard(
      title: "title",
      description: "description",
      day: 3,
      userPref: false,
      complete: false,
    ),
  ],
  [
    LectureCard(
        title: "title",
        description: "description",
        day: 3,
        userPref: true,
        complete: true),
    const SizedBox(height: 16),
    LectureCard(
        title: "title",
        description: "description",
        day: 3,
        userPref: false,
        complete: false),
    const SizedBox(height: 16),
    LectureCard(
        title: "title",
        description: "description",
        day: 3,
        userPref: false,
        complete: false),
    const SizedBox(height: 16),
    LectureCard(
        title: "title",
        description: "description",
        day: 3,
        userPref: false,
        complete: false),
    const SizedBox(height: 16),
    LectureCard(
      title: "title",
      description: "description",
      day: 3,
      userPref: false,
      complete: false,
    ),
  ],
  [
    LectureCard(
        title: "title",
        description: "description",
        day: 3,
        userPref: true,
        complete: true),
    const SizedBox(height: 16),
    LectureCard(
        title: "title",
        description: "description",
        day: 3,
        userPref: false,
        complete: false),
    const SizedBox(height: 16),
    LectureCard(
        title: "title",
        description: "description",
        day: 3,
        userPref: false,
        complete: false),
    const SizedBox(height: 16),
    LectureCard(
        title: "title",
        description: "description",
        day: 3,
        userPref: false,
        complete: false),
    const SizedBox(height: 16),
    LectureCard(
      title: "title",
      description: "description",
      day: 3,
      userPref: false,
      complete: false,
    ),
  ],
  [
    LectureCard(
        title: "title",
        description: "description",
        day: 3,
        userPref: true,
        complete: true),
    const SizedBox(height: 16),
    LectureCard(
        title: "title",
        description: "description",
        day: 3,
        userPref: false,
        complete: false),
    const SizedBox(height: 16),
    LectureCard(
        title: "title",
        description: "description",
        day: 3,
        userPref: false,
        complete: false),
    const SizedBox(height: 16),
    LectureCard(
        title: "title",
        description: "description",
        day: 3,
        userPref: false,
        complete: false),
    const SizedBox(height: 16),
    LectureCard(
      title: "title",
      description: "description",
      day: 3,
      userPref: false,
      complete: false,
    ),
  ]
];
